# -*- org-export-babel-evaluate: nil; -*-
#+title: OMG JavaScript
#+date: <2020-01-13 一 16:52>
#+author: lagagain
#+options: toc:nil
#+export_file_name: ../docs/OMG_js

* 前言
  稍微看了一下[[https://download.microsoft.com/download/C/6/0/C60E2BD0-8A7C-479F-851E-8B5810C0D70F/20130504_MVP_Track3_Session6.pdf][TypeScript 開發實戰]]、[[https://download.microsoft.com/download/7/8/D/78D289B4-CC63-4EA8-BB40-0C957C64F013/20160510_InnovativeApplicationsDevelopmentConference_session7.pdf][使用 TypeScript 駕馭]]。我以為我js算熟...還是有東西和我想得不同...簡單嘗試了一下裡頭的範例。

  測試的node.js版本：

  #+begin_src sh :results output :exports results
node --version
  #+end_src

  #+RESULTS:
  : v12.13.0


* 各個範例嘗試
** 'string' 和 String不同

   #+name: string_vs_String
   #+begin_src js :results output :exports both
   var o1 = 'Hello World';
   var o2 = new String('Hello World');
   console.log("o1 == o2: ", o1 == o2) // true
   console.log("o1 === o2: ", o1 === o2) // false
   console.log("typeof o1: ", typeof o1) // 'string'
   console.log("typeof o2: ", typeof o2) // 'object
   #+end_src

   #+RESULTS: string_vs_String
   : o1 == o2:  true
   : o1 === o2:  false
   : typeof o1:  string
   : typeof o2:  object

   原來 =new String()= 和原生 =string= 出來的不是同個類別...

   #+name: string_instanceis?
   #+begin_src js :results output :exports both
   var o1 = 'Hello World';
   var o2 = new String('Hello World');
   console.log("o2 instanceof String: ", o2 instanceof String) // true
   console.log("o1 instanceof String: ", o1 instanceof String) // false

   try{
     o1 instanceof string // Erro, not define string
   }catch (e){
     console.debug(e)
   }
   #+end_src

   #+RESULTS: string_instanceis?
   #+begin_example
   o2 instanceof String:  true
   o1 instanceof String:  false
   ReferenceError: string is not defined
       at Object.<anonymous> (/tmp/babel-18852wT2/js-script-18852pye:7:17)
       at Module._compile (internal/modules/cjs/loader.js:956:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
       at Module.load (internal/modules/cjs/loader.js:812:32)
       at Function.Module._load (internal/modules/cjs/loader.js:724:14)
       at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
       at internal/main/run_main_module.js:17:11
   #+end_example


*** 但是'string'會受到String.prototype影響...

    ='string'= 不能增加屬性或方法

    #+name: string_cant_add_method
    #+begin_src js :results output :exports both
    var car = 'Hello World';
    car.name = "BMW";
    car.start = function() {
        return true;
    }

    try{
      car.start();
    }catch(e){
      console.debug(e);
    }
    /*
    Thrown:
    TypeError: car.start is not a function
    ,*/

    console.log("car: ", car) // 'Hello World'
    #+end_src

    #+RESULTS: string_cant_add_method
    : TypeError: car.start is not a function
    :     at Object.<anonymous> (/tmp/babel-18852wT2/js-script-18852CbA:8:7)
    :     at Module._compile (internal/modules/cjs/loader.js:956:30)
    :     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    :     at Module.load (internal/modules/cjs/loader.js:812:32)
    :     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    :     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    :     at internal/main/run_main_module.js:17:11
    : car:  Hello World

    但是 =String= 產生的物件可以...

    #+name: but_String_can
    #+begin_src js :results output :exports both
    var car = new String('Hello World');
    car.name = "BMW";
    car.start = function() {
    return true;
    }
    console.log("car.start(): ", car.start()); // true
    console.log("car: ", car) // [String: 'Hello Wrold'] { name: 'BMW', start: [Function] }
    #+end_src

    #+RESULTS: but_String_can
    : car.start():  true
    : car:  [String: 'Hello World'] { name: 'BMW', start: [Function] }

    兩個都會受到 =String.prototype= 的影響Orz...

    #+name: String.prototype_to_string
    #+begin_src js :results output :exports both
    var car = 'Hello World';
    String.prototype.name = "BMW";
    String.prototype.start = function()
    {
      return true;
    }
    var txt = 'Will';

    console.log("txt.name: ", txt.name) // "BMW"
    #+end_src

    #+RESULTS: String.prototype_to_string
    : txt.name:  BMW

    --------

    #+name: String.prototype_to_String
    #+begin_src js :results output :exports both
    var car = new String('Hello World');
    String.prototype.name = "BMW";
    String.prototype.start = function()
    {
      return true;
    }
    var txt = 'Will';
    console.log("txt.name: ", txt.name) // "BMW"
    #+end_src

    #+RESULTS: String.prototype_to_String
    : txt.name:  BMW

    因為他們的 =prototype= 指向同一個物件...

    #+name: String.prototype_and_string.prototype
    #+begin_src js :results output :exports both
    o1 = new String("Hello, World")
    o2 = "Hello, World"

    console.log("o1 === o2: ", o1 === o2) // false
    console.log("o1.prototype  === o2.prototype: ", o1.prototype  === o2.prototype) // ture
    #+end_src

    #+RESULTS: String.prototype_and_string.prototype
    : o1 === o2:  false
    : o1.prototype  === o2.prototype:  true


** 兩個等號和三個等號

#+begin_src js :results output :exports both
  console.log("1 == 1: ", 1 == 1)
  console.log("1 === 1: ", 1 === 1)
  console.log("1 == 1 == 1: ", 1 == 1 == 1)
  console.log("1 === 1 === 1: ", 1 === 1 === 1)

  console.log('"abc" == "abc": ', "abc" == "abc")
  console.log('"abc" === "abc": ', "abc" === "abc")
  console.log('"abc" == "abc" == "abc": ', "abc" == "abc" == "abc")
  console.log('"abc" === "abc" === "abc": ', "abc" === "abc" === "abc")

  console.log("----------------------")

  console.log('1 == true: ', 1 == true)
  console.log('1 === true: ', 1 === true)
  console.log('10 == true: ', 10 == true)
#+end_src

#+RESULTS:
#+begin_example
1 == 1:  true
1 === 1:  true
1 == 1 == 1:  true
1 === 1 === 1:  false
"abc" == "abc":  true
"abc" === "abc":  true
"abc" == "abc" == "abc":  false
"abc" === "abc" === "abc":  false
----------------------
1 == true:  true
1 === true:  false
10 == true:  false
#+end_example


** Function

   #+name: function_instances
   #+begin_src js :results output :exports both
   var o1 = function() {}
   var o2 = new Function();
   console.log("o1 == o2: ", o1 == o2) // false
   console.log("o1 === o2: ", o1 === o2) // false
   console.log("typeof o1: ", typeof o1) // function
   console.log("typeof o2: ", typeof o2) // function
   #+end_src


   #+RESULTS: function_instances
   : o1 == o2:  false
   : o1 === o2:  false
   : typeof o1:  function
   : typeof o2:  function


** Number
   CLOSED: [2020-01-27 一 16:40]
   :LOGBOOK:
   - State "DONE"       from "NEXT"       [2020-01-27 一 16:40]
   :END:

=Number= 有兩個靜態屬性 =MAX_SAFE_INTEGER= 和 =MAX_VALUE=
（還有 =MIN_VALUE= ，不過這邊只先討論一邊的情況）

=MAX_VALUE= 和 =MIN_VALUE= 表示了 =Number= 可以表示的範圍，超過有可能就會變成 =Infinity= 或是 =NaN= 。儘管如此， =Number= 從電腦科學上來看，除了整數還包含了浮點數，其 =MAX_VALUE= 和 =MIN_VALUE= 通常以科學記號表示。而其整數，雖然可以表示大數，卻存在安全界線，依規定其值是 =2^53= 內。看看以下範例：

#+name: integer range
#+begin_src js :results output :exports both
  console.log("Number.MAX_SAFE_INTEGER: ", Number.MAX_SAFE_INTEGER)
  console.log("2**53 - 1== Number.MAX_SAFE_INTEGER: ", 2**53 - 1== Number.MAX_SAFE_INTEGER)

  a = 2**53

  console.log("a: ", a)
  console.log("a == a + 1: ", a == a + 1)
  console.log("a == a + 2: ", a == a + 2)
  console.log("a == a + 3: ", a == a + 3)

  console.log("a + 1: ", a + 1)
  console.log("a + 2: ", a + 2)
  console.log("a + 3: ", a + 3)

  console.log("Number.MAX_SAFE_INTEGER < MAX_VALUE: ", Number.MAX_SAFE_INTEGER < Number.MAX_VALUE)

  console.log("Number.MAX_VALUE: ", Number.MAX_VALUE)
  console.log("Number.MIN_VALUE: ", Number.MIN_VALUE)
#+end_src

Output:

#+RESULTS: integer range
#+begin_example
Number.MAX_SAFE_INTEGER:  9007199254740991
2**53 - 1== Number.MAX_SAFE_INTEGER:  true
a:  9007199254740992
a == a + 1:  true
a == a + 2:  false
a == a + 3:  false
a + 1:  9007199254740992
a + 2:  9007199254740994
a + 3:  9007199254740996
Number.MAX_SAFE_INTEGER < MAX_VALUE:  true
Number.MAX_VALUE:  1.7976931348623157e+308
Number.MIN_VALUE:  5e-324
#+end_example

=a + 1= 值竟與 =a= 相等？？這是因為EMCAScript無法正常表示 =9007199254740993= ，會得到 =9007199254740992= ，所以可能還會看到以下奇怪現象：

#+begin_src js :results output :exports both
  var a = Number.MAX_SAFE_INTEGER + 1 // 9007199254740992

  for(var i = 0; i < 5; i++){
    a = a + 1;
    console.log(a)
  }
#+end_src

這結果會全顯示 =9007199254740992= 。

#+RESULTS:
: 9007199254740992
: 9007199254740992
: 9007199254740992
: 9007199254740992
: 9007199254740992


在負數也有相同情況：

#+begin_src js :results output :exports both
  var a = Number.MAX_SAFE_INTEGER + 1 // 9007199254740992
  a = -a
  for(var i = 0; i < 5; i++){
    a = a - 1;
    console.log(a)
  }
#+end_src

Output:

#+RESULTS:
: -9007199254740992
: -9007199254740992
: -9007199254740992
: -9007199254740992
: -9007199254740992


越過 =9007199254740993= 後不代表就正常了

#+begin_src js :results output :exports both
  var a = Number.MAX_SAFE_INTEGER + 1 // 9007199254740992
  a = a +2
  for(var i = 0; i < 5; i++){
    a = a + 1;
    console.log(a)
  }
#+end_src

在我測試的環境下，上面程式碼依然呈現相同數字：

#+RESULTS:
: 9007199254740996
: 9007199254740996
: 9007199254740996
: 9007199254740996
: 9007199254740996


儘管加法看上去有變，卻可能是錯誤的數值。

#+begin_src js :results output :exports both
  var a = Number.MAX_SAFE_INTEGER + 1 // 9007199254740992
  var pre_str = "900719925474099"
  a = a + 2 // 9007199254740992
  for(var i = 0; i < 5; i++){
    var last_str = (i+4).toString();
    console.log(`a + ${i}: `, a + i)
    console.log(`a + ${i} == ${pre_str + last_str}: `, (a + i).toString() == (pre_str + last_str))
    console.log("------------")
  }
#+end_src


Output:

#+RESULTS:
#+begin_example
a + 0:  9007199254740994
a + 0 == 9007199254740994:  true
------------
a + 1:  9007199254740996
a + 1 == 9007199254740995:  false
------------
a + 2:  9007199254740996
a + 2 == 9007199254740996:  true
------------
a + 3:  9007199254740996
a + 3 == 9007199254740997:  false
------------
a + 4:  9007199254740998
a + 4 == 9007199254740998:  true
------------
#+end_example


* 其他資料

  - [[http://zero.milosz.ca/][Zero in JavaScript]]
